### ISSUE TITLE
pasting specific question link to browser - empty navbar

### ISSUE THREAD

**Issue by compostus** [vrockai/angular-frasque#12]
Take Question title link, paste it to another tab or browser. No path is shown in navbar, so user does not know to what category the question belongs.
![frasque-issue-01](https://cloud.githubusercontent.com/assets/3842536/3007030/e51f3b88-de64-11e3-9ce8-9e4de61db530.png)

**Comment by ICfl** [comment]
Fixed.
a06d976bff6d06c45167e9e15dd45e7f486e7703

**Comment by compostus** [comment]
Thanx Vladko! :smile:
